/**
 * Provider contract verification for patient and payment API endpoints.
 *
 * Reads pact files generated by the web consumer tests and verifies
 * the real API satisfies every defined interaction.
 *
 * Closes #1035 — Contract Testing
 *
 * Prerequisites:
 *   1. Run consumer tests: npm run test:contract --workspace=web
 *   2. Run provider verification: npm run test:contract --workspace=api
 */
import path from 'path';
import { Verifier } from '@pact-foundation/pact';
import { MongoMemoryServer } from 'mongodb-memory-server';
import mongoose from 'mongoose';

const PACT_DIR = path.resolve(__dirname, '../../../../pacts');
const API_PORT = 3098; // isolated port for patient/payment contract verification

let mongod: MongoMemoryServer;

async function startTestServer(): Promise<{ close: () => void }> {
  const { default: app } = await import('../app');
  return new Promise((resolve) => {
    const server = app.listen(API_PORT, () => resolve(server));
  });
}

describe('Patients & Payments API provider contract verification', () => {
  let server: { close: () => void };

  beforeAll(async () => {
    mongod = await MongoMemoryServer.create();
    process.env.MONGO_URI = mongod.getUri();
    process.env.NODE_ENV = 'test';
    process.env.JWT_ACCESS_TOKEN_SECRET = 'test-access-secret-32-chars-long!!';
    process.env.JWT_REFRESH_TOKEN_SECRET = 'test-refresh-secret-32-chars-long!';

    await mongoose.connect(process.env.MONGO_URI);

    // Seed minimal data so state handlers have records to return
    const clinicId = new mongoose.Types.ObjectId();

    const PatientModel = mongoose.model(
      'ContractPatient',
      new mongoose.Schema(
        {
          _id: mongoose.Schema.Types.ObjectId,
          firstName: String,
          lastName: String,
          systemId: String,
          isActive: Boolean,
          clinicId: mongoose.Schema.Types.ObjectId,
        },
        { collection: 'patients' }
      )
    );

    await PatientModel.create({
      _id: new mongoose.Types.ObjectId(),
      firstName: 'Jane',
      lastName: 'Doe',
      systemId: 'PAT-001',
      isActive: true,
      clinicId,
    });

    server = await startTestServer();
  }, 60000);

  afterAll(async () => {
    server.close();
    await mongoose.disconnect();
    await mongod.stop();
  });

  it('satisfies all interactions defined in the patients-payments consumer pact', async () => {
    const verifier = new Verifier({
      provider: 'health-watchers-api',
      providerBaseUrl: `http://localhost:${API_PORT}`,
      pactUrls: [path.join(PACT_DIR, 'health-watchers-web-health-watchers-api.json')],
      logLevel: 'warn',
      stateHandlers: {
        'patients exist for the authenticated clinic': async () => {
          // Seeded in beforeAll
        },
        'a patient with ID patient-id-1 exists': async () => {
          // The provider returns whatever exists; contract verifies shape
        },
        'no patient with ID nonexistent-id exists': async () => {
          // Nothing to set up — the API naturally returns 404
        },
        'payments exist for the authenticated clinic': async () => {
          // Minimal state; shape verified by pact
        },
        'the authenticated clinic has a funded Stellar account': async () => {
          // Payment creation will be handled by the live handler
        },
        'the API is running': async () => {
          // Always true
        },
        'a registered user exists with email doctor@clinic.com': async () => {
          // Handled by auth provider test
        },
        'a valid refresh token exists': async () => {
          // Handled by auth provider test
        },
        'no valid refresh token exists for the given value': async () => {
          // Handled by auth provider test
        },
      },
    });

    await verifier.verifyProvider();
  });
});
