/**
 * Drug–drug interaction database (Issue #1244)
 *
 * Curated pairwise interaction records derived from FDA/CDC labeling and
 * standard clinical references. Entries are keyed by generic drug name so
 * they resolve deterministically against the drug catalog.
 *
 * Severity levels:
 *   critical — contraindicated; avoid combination
 *   major    — clinically significant; requires monitoring or dose adjustment
 *   moderate — may require therapy modification
 *   minor    — limited clinical effect
 *
 * The bundled data is versioned; `POST /interactions/refresh` can import
 * additional rows (e.g. updated CDC/FDA exports) into the database, which are
 * merged with this baseline at check time.
 */

export type InteractionSeverity = 'critical' | 'major' | 'moderate' | 'minor';

export interface DrugInteractionRecord {
  drugA: string;
  drugB: string;
  severity: InteractionSeverity;
  mechanism: string;
  management: string;
  source: string;
}

export const INTERACTION_DATA: DrugInteractionRecord[] = [
  // ── Critical (contraindicated) ─────────────────────────────────────────────
  {
    drugA: 'phenelzine',
    drugB: 'fluoxetine',
    severity: 'critical',
    mechanism: 'Additive serotonergic activity — risk of serotonin syndrome.',
    management:
      'Avoid combination. Allow a 5-week washout after fluoxetine before starting an MAOI.',
    source: 'FDA',
  },
  {
    drugA: 'tranylcypromine',
    drugB: 'sertraline',
    severity: 'critical',
    mechanism: 'Additive serotonergic activity — risk of serotonin syndrome.',
    management: 'Avoid combination. Requires washout between agents.',
    source: 'FDA',
  },
  {
    drugA: 'phenelzine',
    drugB: 'tramadol',
    severity: 'critical',
    mechanism: 'Serotonin syndrome risk combined with opioid pharmacology.',
    management: 'Contraindicated — do not co-administer.',
    source: 'FDA',
  },
  {
    drugA: 'tranylcypromine',
    drugB: 'amitriptyline',
    severity: 'critical',
    mechanism: 'Hypertensive crisis and serotonin syndrome risk.',
    management: 'Contraindicated — do not co-administer.',
    source: 'FDA',
  },
  {
    drugA: 'selegiline',
    drugB: 'meperidine',
    severity: 'critical',
    mechanism: 'Fatal serotonin syndrome risk.',
    management: 'Contraindicated — do not co-administer.',
    source: 'FDA',
  },
  {
    drugA: 'sildenafil',
    drugB: 'nitroglycerin',
    severity: 'critical',
    mechanism: 'Additive vasodilation causing profound hypotension.',
    management: 'Contraindicated within 24 hours of nitrate use.',
    source: 'FDA',
  },
  {
    drugA: 'sildenafil',
    drugB: 'isosorbide',
    severity: 'critical',
    mechanism: 'Additive vasodilation causing profound hypotension.',
    management: 'Contraindicated — nitrates must not be co-administered.',
    source: 'FDA',
  },
  {
    drugA: 'tadalafil',
    drugB: 'nitroglycerin',
    severity: 'critical',
    mechanism: 'Additive vasodilation causing profound hypotension.',
    management: 'Contraindicated within 48 hours of nitrate use.',
    source: 'FDA',
  },
  {
    drugA: 'simvastatin',
    drugB: 'clarithromycin',
    severity: 'critical',
    mechanism: 'CYP3A4 inhibition increases simvastatin exposure — rhabdomyolysis risk.',
    management:
      'Contraindicated. If co-administration is unavoidable, suspend simvastatin during therapy.',
    source: 'FDA',
  },
  {
    drugA: 'lovastatin',
    drugB: 'clarithromycin',
    severity: 'critical',
    mechanism: 'CYP3A4 inhibition increases lovastatin exposure — rhabdomyolysis risk.',
    management: 'Contraindicated. Avoid the combination.',
    source: 'FDA',
  },
  {
    drugA: 'erythromycin',
    drugB: 'simvastatin',
    severity: 'critical',
    mechanism: 'CYP3A4 inhibition increases simvastatin exposure — rhabdomyolysis risk.',
    management: 'Contraindicated. Avoid the combination.',
    source: 'FDA',
  },
  {
    drugA: 'ciprofloxacin',
    drugB: 'tizanidine',
    severity: 'critical',
    mechanism:
      'CYP1A2 inhibition markedly increases tizanidine levels — severe hypotension and sedation.',
    management: 'Contraindicated. Do not co-administer.',
    source: 'FDA',
  },
  {
    drugA: 'levofloxacin',
    drugB: 'amiodarone',
    severity: 'critical',
    mechanism: 'Additive QT prolongation — risk of torsades de pointes.',
    management: 'Contraindicated in most patients; avoid the combination.',
    source: 'FDA',
  },
  {
    drugA: 'amiodarone',
    drugB: 'sotalol',
    severity: 'critical',
    mechanism: 'Additive QT prolongation — risk of torsades de pointes.',
    management: 'Contraindicated. Avoid the combination.',
    source: 'FDA',
  },
  {
    drugA: 'oxycodone',
    drugB: 'diazepam',
    severity: 'critical',
    mechanism: 'Additive CNS and respiratory depression.',
    management: 'Contraindicated without dose adjustment and monitoring.',
    source: 'FDA',
  },
  {
    drugA: 'spironolactone',
    drugB: 'potassium',
    severity: 'critical',
    mechanism: 'Additive hyperkalemia risk.',
    management: 'Contraindicated. Monitor potassium closely if unavoidable.',
    source: 'FDA',
  },

  // ── Major ──────────────────────────────────────────────────────────────────
  {
    drugA: 'warfarin',
    drugB: 'aspirin',
    severity: 'major',
    mechanism: 'Additive antiplatelet effect increases bleeding risk.',
    management: 'Avoid unless clearly indicated; monitor INR and for bleeding.',
    source: 'FDA',
  },
  {
    drugA: 'warfarin',
    drugB: 'ibuprofen',
    severity: 'major',
    mechanism: 'NSAID platelet inhibition and GI erosion increase bleeding risk.',
    management: 'Avoid; prefer acetaminophen or monitor INR closely.',
    source: 'FDA',
  },
  {
    drugA: 'warfarin',
    drugB: 'naproxen',
    severity: 'major',
    mechanism: 'NSAID platelet inhibition and GI erosion increase bleeding risk.',
    management: 'Avoid; prefer acetaminophen or monitor INR closely.',
    source: 'FDA',
  },
  {
    drugA: 'warfarin',
    drugB: 'clopidogrel',
    severity: 'major',
    mechanism: 'Additive antithrombotic effect increases bleeding risk.',
    management: 'Monitor closely for bleeding; limit duration of dual therapy.',
    source: 'FDA',
  },
  {
    drugA: 'warfarin',
    drugB: 'fluconazole',
    severity: 'major',
    mechanism: 'CYP2C9 inhibition increases warfarin exposure and INR.',
    management: 'Monitor INR frequently and reduce warfarin dose as needed.',
    source: 'FDA',
  },
  {
    drugA: 'warfarin',
    drugB: 'amiodarone',
    severity: 'major',
    mechanism: 'CYP2C9 inhibition increases warfarin exposure and INR.',
    management: 'Reduce warfarin dose by 30–50% and monitor INR closely.',
    source: 'FDA',
  },
  {
    drugA: 'warfarin',
    drugB: 'rifampin',
    severity: 'major',
    mechanism: 'CYP2C9 induction decreases warfarin effect.',
    management: 'Monitor INR; warfarin dose may need significant increase.',
    source: 'FDA',
  },
  {
    drugA: 'warfarin',
    drugB: 'metronidazole',
    severity: 'major',
    mechanism: 'CYP2C9 inhibition increases warfarin exposure and INR.',
    management: 'Monitor INR and reduce warfarin dose as needed.',
    source: 'FDA',
  },
  {
    drugA: 'simvastatin',
    drugB: 'verapamil',
    severity: 'major',
    mechanism: 'CYP3A4 inhibition increases simvastatin exposure — myopathy risk.',
    management: 'Limit simvastatin to 10 mg/day; monitor for muscle symptoms.',
    source: 'FDA',
  },
  {
    drugA: 'simvastatin',
    drugB: 'diltiazem',
    severity: 'major',
    mechanism: 'CYP3A4 inhibition increases simvastatin exposure — myopathy risk.',
    management: 'Limit simvastatin to 10 mg/day; monitor for muscle symptoms.',
    source: 'FDA',
  },
  {
    drugA: 'simvastatin',
    drugB: 'amiodarone',
    severity: 'major',
    mechanism: 'CYP3A4 inhibition increases simvastatin exposure — myopathy risk.',
    management: 'Limit simvastatin to 20 mg/day; monitor for muscle symptoms.',
    source: 'FDA',
  },
  {
    drugA: 'atorvastatin',
    drugB: 'clarithromycin',
    severity: 'major',
    mechanism: 'CYP3A4 inhibition increases atorvastatin exposure.',
    management: 'Use lowest effective atorvastatin dose; monitor for myopathy.',
    source: 'FDA',
  },
  {
    drugA: 'digoxin',
    drugB: 'amiodarone',
    severity: 'major',
    mechanism: 'Reduced digoxin clearance and additive bradycardia.',
    management: 'Reduce digoxin dose by half and monitor levels.',
    source: 'FDA',
  },
  {
    drugA: 'digoxin',
    drugB: 'verapamil',
    severity: 'major',
    mechanism: 'Increased digoxin levels and additive AV block.',
    management: 'Reduce digoxin dose and monitor levels and rhythm.',
    source: 'FDA',
  },
  {
    drugA: 'digoxin',
    drugB: 'clarithromycin',
    severity: 'major',
    mechanism: 'P-glycoprotein inhibition increases digoxin levels.',
    management: 'Monitor digoxin levels and signs of toxicity.',
    source: 'FDA',
  },
  {
    drugA: 'sotalol',
    drugB: 'citalopram',
    severity: 'major',
    mechanism: 'Additive QT prolongation — risk of torsades de pointes.',
    management: 'Avoid; monitor ECG if unavoidable.',
    source: 'FDA',
  },
  {
    drugA: 'fluoxetine',
    drugB: 'tramadol',
    severity: 'major',
    mechanism: 'Serotonin syndrome and reduced seizure threshold.',
    management: 'Avoid; monitor for serotonin syndrome symptoms.',
    source: 'FDA',
  },
  {
    drugA: 'venlafaxine',
    drugB: 'tramadol',
    severity: 'major',
    mechanism: 'Serotonin syndrome risk.',
    management: 'Avoid; monitor for serotonin syndrome symptoms.',
    source: 'FDA',
  },
  {
    drugA: 'sertraline',
    drugB: 'amitriptyline',
    severity: 'major',
    mechanism: 'CYP2D6 inhibition increases TCA levels — cardiac effects.',
    management: 'Monitor TCA levels and clinical response.',
    source: 'FDA',
  },
  {
    drugA: 'lithium',
    drugB: 'ibuprofen',
    severity: 'major',
    mechanism: 'NSAIDs reduce lithium clearance — toxicity risk.',
    management: 'Avoid; monitor lithium levels if co-administered.',
    source: 'FDA',
  },
  {
    drugA: 'lithium',
    drugB: 'naproxen',
    severity: 'major',
    mechanism: 'NSAIDs reduce lithium clearance — toxicity risk.',
    management: 'Avoid; monitor lithium levels if co-administered.',
    source: 'FDA',
  },
  {
    drugA: 'lithium',
    drugB: 'lisinopril',
    severity: 'major',
    mechanism: 'ACE inhibitors reduce lithium clearance — toxicity risk.',
    management: 'Monitor lithium levels and renal function.',
    source: 'FDA',
  },
  {
    drugA: 'lithium',
    drugB: 'enalapril',
    severity: 'major',
    mechanism: 'ACE inhibitors reduce lithium clearance — toxicity risk.',
    management: 'Monitor lithium levels and renal function.',
    source: 'FDA',
  },
  {
    drugA: 'methotrexate',
    drugB: 'ibuprofen',
    severity: 'major',
    mechanism: 'NSAIDs reduce methotrexate clearance — toxicity risk.',
    management: 'Avoid; particularly at high-dose methotrexate.',
    source: 'FDA',
  },
  {
    drugA: 'lisinopril',
    drugB: 'potassium',
    severity: 'major',
    mechanism: 'Additive hyperkalemia risk.',
    management: 'Monitor potassium; avoid potassium supplements.',
    source: 'FDA',
  },
  {
    drugA: 'lisinopril',
    drugB: 'spironolactone',
    severity: 'major',
    mechanism: 'Additive hyperkalemia risk.',
    management: 'Monitor potassium closely; dose adjust.',
    source: 'FDA',
  },
  {
    drugA: 'enalapril',
    drugB: 'spironolactone',
    severity: 'major',
    mechanism: 'Additive hyperkalemia risk.',
    management: 'Monitor potassium closely; dose adjust.',
    source: 'FDA',
  },
  {
    drugA: 'prednisone',
    drugB: 'ibuprofen',
    severity: 'major',
    mechanism: 'Additive GI ulceration and bleeding risk.',
    management: 'Use gastroprotection; limit NSAID duration.',
    source: 'FDA',
  },
  {
    drugA: 'prednisone',
    drugB: 'naproxen',
    severity: 'major',
    mechanism: 'Additive GI ulceration and bleeding risk.',
    management: 'Use gastroprotection; limit NSAID duration.',
    source: 'FDA',
  },
  {
    drugA: 'fluconazole',
    drugB: 'simvastatin',
    severity: 'major',
    mechanism: 'CYP3A4 inhibition increases simvastatin exposure.',
    management: 'Avoid; if needed, suspend statin during azole therapy.',
    source: 'FDA',
  },
  {
    drugA: 'carbamazepine',
    drugB: 'clarithromycin',
    severity: 'major',
    mechanism: 'CYP3A4 inhibition increases carbamazepine levels — toxicity.',
    management: 'Monitor carbamazepine levels and signs of toxicity.',
    source: 'FDA',
  },
  {
    drugA: 'phenytoin',
    drugB: 'fluconazole',
    severity: 'major',
    mechanism: 'CYP2C9 inhibition increases phenytoin levels.',
    management: 'Monitor phenytoin levels; adjust dose.',
    source: 'FDA',
  },
  {
    drugA: 'methadone',
    drugB: 'diazepam',
    severity: 'major',
    mechanism: 'Additive CNS and respiratory depression.',
    management: 'Use lowest doses; monitor respiration.',
    source: 'FDA',
  },
  {
    drugA: 'clopidogrel',
    drugB: 'omeprazole',
    severity: 'moderate',
    mechanism: 'CYP2C19 inhibition reduces clopidogrel activation.',
    management: 'Prefer pantoprazole or another PPI; consider alternate antiplatelet.',
    source: 'FDA',
  },
  {
    drugA: 'clopidogrel',
    drugB: 'esomeprazole',
    severity: 'moderate',
    mechanism: 'CYP2C19 inhibition reduces clopidogrel activation.',
    management: 'Prefer a PPI with less CYP2C19 inhibition.',
    source: 'FDA',
  },
  {
    drugA: 'digoxin',
    drugB: 'spironolactone',
    severity: 'moderate',
    mechanism: 'Spironolactone may interfere with digoxin assays and reduce clearance.',
    management: 'Monitor digoxin levels.',
    source: 'FDA',
  },
  {
    drugA: 'citalopram',
    drugB: 'fluconazole',
    severity: 'moderate',
    mechanism: 'CYP2C19 inhibition increases citalopram levels and QT risk.',
    management: 'Limit citalopram dose; monitor QT.',
    source: 'FDA',
  },
  {
    drugA: 'lisinopril',
    drugB: 'ibuprofen',
    severity: 'moderate',
    mechanism: 'NSAIDs reduce antihypertensive effect and impair renal function.',
    management: 'Monitor BP and renal function.',
    source: 'FDA',
  },
  {
    drugA: 'lisinopril',
    drugB: 'naproxen',
    severity: 'moderate',
    mechanism: 'NSAIDs reduce antihypertensive effect and impair renal function.',
    management: 'Monitor BP and renal function.',
    source: 'FDA',
  },
  {
    drugA: 'aspirin',
    drugB: 'clopidogrel',
    severity: 'moderate',
    mechanism: 'Additive antiplatelet effect increases bleeding risk.',
    management: 'Use only when indicated (e.g. recent ACS/stent); minimize duration.',
    source: 'FDA',
  },
  {
    drugA: 'levothyroxine',
    drugB: 'omeprazole',
    severity: 'moderate',
    mechanism: 'Reduced gastric acidity impairs levothyroxine absorption.',
    management: 'Monitor TSH; separate administration times.',
    source: 'FDA',
  },
  {
    drugA: 'doxycycline',
    drugB: 'warfarin',
    severity: 'moderate',
    mechanism: 'Altered gut flora may potentiate warfarin effect.',
    management: 'Monitor INR during and after antibiotic course.',
    source: 'FDA',
  },
  {
    drugA: 'ciprofloxacin',
    drugB: 'warfarin',
    severity: 'moderate',
    mechanism: 'CYP1A2 inhibition and altered flora increase INR.',
    management: 'Monitor INR closely.',
    source: 'FDA',
  },
];

export const INTERACTION_DATA_VERSION = '2026.1';
